---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
 - ../../base/operator
 - ../../base/instance

resources:
 # - https://raw.githubusercontent.com/skupperproject/skupper/1.4.0-rc1/cmd/site-controller/deploy-watch-current-ns.yaml
  - link-to-central-secret.yaml
  - link-to-central-policy.yaml

patches:
-  target:
     kind: ConfigMap
     name: skupper-site
   patch: |-
    - op: replace
      path: /data/name
      value: ocpmgt
    - op: replace
      path: /data/console-authentication
      value: openshift
