---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  # - ../../base/site-controller
  - ../../base/operator
  - ../../base/instance

patches:
- target:
    kind: ConfigMap
    name: skupper-site
  patch: |-
   - op: replace
     path: /data/name
     value: ai-one
